repositories:
- name: test-app
  url: git+https://github.com/edorso-dinum/test-app.git

releases:
- name: opicloud-dev-osc-euw2-wapp-01
  chart: test-app
  namespace: default
  verify: false
  missingFileHandler: Warn
  values:
    - values.yaml
