apiVersion: v1
kind: Service
metadata:
  name: {{ include "website.fullname" . }}
  namespace: {{ include "website.namespace" . | quote }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    {{- include "website.selectorLabels" . | nindent 4 }}
