-- Expects to be run against the `doublures` PostgreSQL database
-- (provisioned by the CNPG cluster), e.g. `psql -d doublures -f doublure.sql`.
CREATE TABLE IF NOT EXISTS doublure_names (
    firstname VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL
);

TRUNCATE TABLE doublure_names;

INSERT INTO doublure_names (firstname, name) VALUES
    ('Christopher', 'Cook'),
    ('Donna', 'Hill'),
    ('George', 'Price'),
    ('Michael', 'Long'),
    ('Karen', 'Foster'),
    ('Jacob', 'Rogers'),
    ('Jessica', 'Gray'),
    ('Jennifer', 'Patel'),
    ('Brandon', 'Bryant'),
    ('Jessica', 'Hughes'),
    ('David', 'Long'),
    ('Samuel', 'Green'),
    ('Larry', 'Foster'),
    ('Donna', 'Roberts'),
    ('Eric', 'Flores'),
    ('Nicole', 'Murphy'),
    ('Ruth', 'Clark'),
    ('Nicole', 'Lopez'),
    ('Karen', 'Bennett'),
    ('Brian', 'Young'),
    ('Stephanie', 'Bryant'),
    ('Janet', 'Torres'),
    ('Emily', 'Jenkins'),
    ('Sarah', 'Bennett'),
    ('Michelle', 'Patterson'),
    ('Ashley', 'Miller'),
    ('Adam', 'Ward'),
    ('Alexander', 'Torres'),
    ('Nancy', 'Sanders'),
    ('Michelle', 'Patel'),
    ('Brian', 'Bennett'),
    ('Donna', 'Hall'),
    ('Emma', 'Thompson'),
    ('Robert', 'Young'),
    ('William', 'Baker'),
    ('Stephen', 'Bryant'),
    ('Mark', 'Jenkins'),
    ('Jerry', 'Thompson'),
    ('Jerry', 'Bennett'),
    ('Susan', 'Hughes'),
    ('George', 'Mitchell'),
    ('Kevin', 'Patel'),
    ('Catherine', 'Reyes'),
    ('Dorothy', 'Baker'),
    ('Alexander', 'Clark'),
    ('Henry', 'Reyes'),
    ('Jennifer', 'Robinson'),
    ('Jack', 'Hall'),
    ('Sharon', 'Perez'),
    ('John', 'Hill'),
    ('Nathan', 'Jenkins'),
    ('Janet', 'Simmons'),
    ('Jacob', 'Simmons'),
    ('Dorothy', 'Miller'),
    ('George', 'Price'),
    ('Jeffrey', 'Robinson'),
    ('Karen', 'Evans'),
    ('Christopher', 'Smith'),
    ('Eric', 'Flores'),
    ('Carl', 'Morris'),
    ('Daniel', 'Bennett'),
    ('Carl', 'Martin'),
    ('Christine', 'Cruz'),
    ('Peter', 'Jones'),
    ('Christopher', 'Jenkins'),
    ('Susan', 'Turner'),
    ('Christopher', 'Sanders'),
    ('Donald', 'Thompson'),
    ('Emily', 'Roberts'),
    ('Janet', 'Perry'),
    ('Jason', 'Perry'),
    ('Michael', 'Lee'),
    ('Brandon', 'Bryant'),
    ('David', 'Smith'),
    ('Robert', 'Thompson'),
    ('Gregory', 'Powell'),
    ('Ryan', 'Gonzales'),
    ('Amanda', 'White'),
    ('Melissa', 'Parker');
